OPENAI_API_TYPE = "azure"
OPENAI_API_BASE = "https://contact-center-llm-ws-eu.openai.azure.com/"
OPENAI_API_KEY = "e1ab0f94d3514373b12e519d1860bde8"
OPENAI_API_VERSION = "2023-03-15-preview"
OPENAI_MODEL = "gpt-35-turbo"
OPENAI_EMBEDDINGS = "text-embedding-ada-002"
